Apply @coderabbitai reviews - clean schemathesis code - add test to build phase in fron dockerfile - remove unused dependencies from back - add better config files error handling - fix bad definition of deletUser in backend - add error handling to /db/populateèdb.py

diff --git a/junqo_front/dockerfile.dev b/junqo_front/dockerfile.dev
--- a/junqo_front/dockerfile.dev
+++ b/junqo_front/dockerfile.dev
@@ -45,6 +45,7 @@ RUN dart run build_runner build --delete-conflicting-outputs
 
 # Build the app
 RUN flutter build web
+RUN test -d build/web || (echo "Error when building the web app, web build not found" && exit 1)
 
 # Clean up unnecessary files to reduce image size
 RUN rm -rf /usr/local/src/flutter
