Enable WebAssembly support in Flutter build process

diff --git a/junqo_front/dockerfile.dev b/junqo_front/dockerfile.dev
--- a/junqo_front/dockerfile.dev
+++ b/junqo_front/dockerfile.dev
@@ -44,9 +44,9 @@ RUN flutter pub get
 
 # Build the app
 RUN if [ -n "$API_URL" ]; then \
-    flutter build web --dart-define=API_URL=$API_URL; \
+    flutter build web --wasm --debug --dart-define=API_URL=$API_URL; \
     else \
-    flutter build web; \
+    flutter build web --wasm --debug; \
     fi
 RUN test -d build/web || (echo "Error when building the web app, web build not found" && exit 1)
 
@@ -54,7 +54,7 @@ RUN test -d build/web || (echo "Error when building the web app, web build not f
 RUN rm -rf /usr/local/src/flutter
 
 # Stage 2 - Create the run-time image
-FROM nginx:1.21.1-alpine
+FROM nginx:1.29.2-alpine
 
 HEALTHCHECK --interval=5s --timeout=5s --start-period=5s --retries=5 \
     CMD curl -f http://localhost || exit 1
@@ -62,5 +62,6 @@ HEALTHCHECK --interval=5s --timeout=5s --start-period=5s --retries=5 \
 COPY --from=build-env /home/app/junqo_front/build/web /usr/share/nginx/html
 COPY --chown=nginx:nginx ./junqo_front/nginx.conf /etc/nginx/nginx.conf
 RUN test -f /etc/nginx/nginx.conf || (echo "Nginx config not found" && exit 1) && chmod 644 /etc/nginx/nginx.conf
+RUN test -e /usr/share/nginx/html/flutter_service_worker.js || (echo "Error when building the web app, web build not found" && exit 1)
 
 EXPOSE 80
